apiVersion: v1
kind: Secret
metadata:
  name: finspot-registry
  namespace: asset-manager
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJmcy1sZS1kZXYtaGFyYm9yLmZpbnNwb3QuaW4iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoialBHTXA1TUZIZzZBYzZhY3JZMkphZWdlUUxnU0NEMyIsImF1dGgiOiJZV1J0YVc0NmFsQkhUWEExVFVaSVp6WkJZelpoWTNKWk1rcGhaV2RsVVV4blUwTkVNdz09In19fQ==
