apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asset-manager
  namespace: asset-manager
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argus.finspot.in
      secretName: finspot-tls
  rules:
    - host: argus.finspot.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: asset-manager-web
                port:
                  number: 80
